version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          GO111MODULE: "ON"
    working_directory: /go/src/github.com/y0c/
    steps:
      - checkout
      - run: go build
      - run: go run main.go 
