version: 2
jobs:
  build:
    docker:
      - image: holnet1026/circleci-serverless-go:latest
    working_directory: /go/src/github.com/y0c
    steps:
      - checkout
      - run: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - run: go get -u github.com/aws/aws-lambda-go/lambda
      - run: make deploy
